CHAINS = set([
    "A&W Restaurants",
    "America's Incredible Pizza Company",
    "Applebee's",
    "Arby's",
    "Arctic Circle Restaurants",
    "Arthur Treacher's Fish & Chips",
    "Atlanta Bread Company",
    "Auntie Anne's",
    "Bahama Breeze",
    "Baja Fresh",
    "Bakers Square",
    "Baskin-Robbins",
    "Beef O'Brady's",
    "Ben & Jerry's",
    "Benihana",
    "Bennigan's",
    "Bertucci's",
    "Big Boy",
    "Bikinis Sports Bar & Grill",
    "BJ's Restaurant & Brewery",
    "Black Angus Steakhouse",
    "Black-eyed Pea",
    "Blimpie",
    "Bob Evans Restaurants",
    "Bojangles' Famous Chicken 'n Biscuits",
    "Bonefish Grill",
    "Boston Market",
    "Braum's",
    "Bravo!, Cucina Italiana",
    "Brio",
    "Bubba Gump Shrimp Company",
    "Buca di Beppo",
    "Buffalo Wild Wings",
    "Burger King",
    "Burger Street",
    "Burgerville",
    "Cafe Rio",
    "California Pizza Kitchen",
    "California Tortilla",
    "Camille's Sidewalk Cafe",
    "Captain D's",
    "The Capital Grille",
    "Carino's Italian Grill",
    "Carl's Jr.",
    "Carrabba's Italian Grill",
    "Carrows",
    "Carvel Ice Cream",
    "Champps Americana",
    "Charley's Grilled Subs",
    "Charlie Brown's Fresh Grill",
    "Checkers",
    "Cheeburger Cheeburger",
    "Cheeseburger in Paradise",
    "Cheesecake Factory",
    "Cheddar's Casual Café",
    "Chevys Fresh Mex",
    "Chicken Express",
    "Chick-fil-A",
    "Chili's",
    "Chipotle Mexican Grill",
    "Chronic Tacos",
    "Chuck-A-Rama",
    "Chuck E. Cheese's",
    "Church's",
    "CiCi's Pizza",
    "Cinnabon",
    "Claim Jumper",
    "Coco's Bakery",
    "Cold Stone Creamery",
    "Copeland's",
    "Country Buffet",
    "Cracker Barrel Old Country Store",
    "Culver's",
    "Dairy Queen",
    "Damon's Grill",
    "Dave & Buster's",
    "Denny's",
    "Del Taco",
    "Dickey's Barbecue Pit",
    "Dixie Chili and Deli",
    "Domino's Pizza",
    "Don Pablo's",
    "Donatos Pizza",
    "Dunkin' Donuts",
    "East of Chicago Pizza",
    "EatZi's",
    "Eat'n Park",
    "Eegee's",
    "El Chico",
    "El Pollo Loco",
    "Elephant Bar",
    "El Taco Tote",
    "Famous Dave's",
    "Farmer Boys",
    "Fatburger",
    "FATZ",
    "Fazoli's",
    "Five Guys Famous Burgers and Fries",
    "Fleming's Prime Steakhouse & Wine Bar",
    "Freddy's Frozen Custard & Steakburgers",
    "Freebirds World Burrito",
    "Fresh Choice",
    "Friendly's",
    "Fuddruckers",
    "Gatti's Pizza",
    "GameWorks",
    "Gino's Pizza and Spaghetti",
    "Godfather's Pizza",
    "Golden Chick",
    "Golden Corral",
    "Green Burrito",
    "Green Mill[disambiguation needed]",
    "Ground Round",
    "Hard Rock Cafe",
    "Hardee's",
    "Hobee's Restaurant",
    "Hooters",
    "Houlihan's",
    "Houston's Restaurant",
    "Howard Johnson's",
    "Huddle House",
    "HuHot Mongolian Grill",
    "Hungry Howie's Pizza",
    "IHOP",
    "In-N-Out Burger",
    "Jack in the Box",
    "Jack's",
    "Jamba Juice",
    "Jason's Deli",
    "Jerry's Subs & Pizza",
    "Jersey Mike's Subs",
    "Jimmy John's",
    "Jim's Restaurants",
    "Joe's Crab Shack",
    "John's Incredible Pizza",
    "Johnny Rockets",
    "Ker's WingHouse",
    "KFC",
    "Krispy Kreme",
    "Krystal",
    "L&L Hawaiian Barbecue",
    "Landry's Restaurants",
    "Ledo Pizza",
    "Lee Roy Selmon's",
    "Lee's Famous Recipe Chicken",
    "Little Caesars",
    "Logan's Roadhouse",
    "Lone Star Steakhouse & Saloon",
    "LongHorn Steakhouse",
    "Long John Silver's",
    "Luby's",
    "Lyon's",
    "Maggiano's Little Italy",
    "Marie Callender's",
    "Max & Erma's",
    "McAlister's Deli",
    "McDonald's",
    "The Melting Pot",
    "Mazzio's Italian Eatery",
    "Miller's Ale House",
    "Milo's Hamburgers",
    "Mitchell's Fish Market",
    "Moe's Southwest Grill",
    "Montana Mike's",
    "Mr. Hero",
    "Mrs. Fields",
    "National Coney Island",
    "Naugles",
    "Noodles & Company",
    "O'Charley's",
    "Old Country Buffet",
    "Olive Garden",
    "On the Border Mexican Grill & Cantina",
    "Outback Steakhouse",
    "The Old Spaghetti Factory",
    "The Original Italian Pie",
    "The Original Pancake House",
    "Panera Bread",
    "Panda Express",
    "Papa Gino's",
    "Papa John's Pizza",
    "Papa Murphy's Take 'N' Bake pizza",
    "Pei Wei Asian Diner",
    "Penn Station (restaurant)",
    "Perkins Restaurant and Bakery",
    "P. F. Chang's China Bistro",
    "Pita Pit",
    "Pizza Hut",
    "Pizza Inn",
    "Pizza Ranch",
    "Planet Hollywood",
    "Ponderosa Steakhouse and Bonanza Steakhouse",
    "Popeyes Chicken & Biscuits",
    "Portillo's Restaurants",
    "Port of Subs",
    "Potbelly Sandwich Works",
    "Qdoba Mexican Grill",
    "Quaker Steak & Lube",
    "Quiznos",
    "RA Sushi",
    "Rainforest Cafe",
    "Rally's",
    "Raising Cane's Chicken Fingers",
    "Rax",
    "Red Hot & Blue",
    "Red Lobster",
    "Red Robin",
    "Redstone American Grill",
    "Robeks",
    "Rock Bottom",
    "Romano's Macaroni Grill",
    "Round Table Pizza",
    "Roy Rogers Restaurants",
    "Roy's",
    "Ruby Tuesday",
    "Rubio's Fresh Mexican Grill",
    "Ruth's Chris Steak House",
    "Runza",
    "Saladworks",
    "Sbarro",
    "Schlotzsky's",
    "Seasons 52",
    "Seattle's Best Coffee",
    "Shake Shack",
    "Shane's Rib Shack",
    "Showmars",
    "Shoney's",
    "Sizzler",
    "Skyline Chili",
    "Smashburger",
    "Smokey Bones",
    "Sneaky Pete's",
    "Sonic Drive-In",
    "Souplantation and Sweet Tomatoes",
    "Spaghetti Warehouse",
    "Spangles",
    "Starbucks",
    "Steak 'n Shake",
    "Sticky Fingers",
    "Stir Crazy",
    "Sub Station II",
    "Subway",
    "Sweet Tomatoes",
    "Swensen's",
    "Swensons",
    "T.G.I. Friday's",
    "Taco Bell",
    "Taco Bueno",
    "Taco Cabana",
    "Taco John's",
    "Taco Mayo",
    "Taco Tico",
    "Taco Time",
    "Texas Roadhouse",
    "Tijuana Flats",
    "Tilted Kilt",
    "Tony Roma's",
    "Trader Vic's",
    "Twin Peaks",
    "Umami Burger",
    "Uncle Maddio's Pizza Joint",
    "Uno Chicago Grill",
    "Valentino's",
    "Village Inn",
    "Waffle House",
    "Wendy's",
    "Wetzel's Pretzels",
    "Whataburger",
    "Which Wich?",
    "White Castle",
    "Wienerschnitzel",
    "Wild Wing Cafe",
    "York Steak House",
    "Zaxby's"
])