#!/usr/bin/env python
# coding: utf-8
#
# Copyright (c) 2015, PAL Team.
# All rights reserved. See LICENSE for details.

FIVE_HUNDRED = set([
    "Wal-Mart Stores",
    "Royal Dutch Shell",
    "Sinopec Group",
    "China National Petroleum",
    "Exxon Mobil",
    "BP",
    "State Grid",
    "Volkswagen",
    "Toyota Motor",
    "Glencore",
    "Total",
    "Chevron",
    "Samsung Electronics",
    "Berkshire Hathaway",
    "Apple",
    "AXA",
    "Gazprom",
    "E.ON",
    "Phillips 66",
    "Daimler",
    "General Motors",
    "ENI",
    "Japan Post Holdings",
    "EXOR Group",
    "Industrial &amp; Commercial Bank of China",
    "Ford Motor",
    "General Electric",
    "Petrobras",
    "McKesson",
    "Valero Energy",
    "Allianz",
    "Hon Hai Precision Industry",
    "Société Générale",
    "AT&amp;T",
    "CVS Caremark",
    "Pemex",
    "Fannie Mae",
    "China Construction Bank",
    "UnitedHealth Group",
    "BNP Paribas",
    "PDVSA",
    "Verizon Communications",
    "Lukoil",
    "GDF Suez",
    "Honda Motor",
    "Rosneft Oil",
    "Agricultural Bank of China",
    "Assicurazioni Generali",
    "ING Group",
    "Hewlett-Packard",
    "JX Holdings",
    "China State Construction Engineering",
    "Nippon Telegraph &amp; Telephone",
    "Statoil",
    "China Mobile Communications",
    "Enel",
    "J.P. Morgan Chase &amp; Co.",
    "Siemens",
    "Bank of China",
    "Costco Wholesale",
    "Nissan Motor",
    "Express Scripts Holding",
    "Tesco",
    "SK Holdings",
    "Carrefour",
    "Bank of America Corp.",
    "Cardinal Health",
    "BMW Group",
    "Petronas",
    "Électricite de France",
    "International Business Machines",
    "Nestlé",
    "Banco Santander",
    "Kroger",
    "BASF",
    "Noble Group",
    "HSBC Holdings",
    "Hitachi",
    "China National Offshore Oil",
    "China Railway Construction",
    "Marathon Petroleum",
    "Citigroup",
    "Credit Agricole",
    "PTT",
    "SAIC Motor",
    "China Railway Group",
    "Archer Daniels Midland",
    "AmerisourceBergen",
    "Wells Fargo",
    "Boeing",
    "Metro",
    "Procter &amp; Gamble",
    "Munich Re Group",
    "Lloyds Banking Group",
    "Prudential",
    "Indian Oil",
    "Freddie Mac",
    "China Life Insurance",
    "Deutsche Telekom",
    "Hyundai Motor",
    "ArcelorMittal",
    "Home Depot",
    "Airbus Group",
    "Microsoft",
    "Sony",
    "Panasonic",
    "Sinochem Group",
    "Mitsubishi",
    "Telefonica",
    "Deutsche Post",
    "China FAW Group",
    "Amazon.com",
    "Dongfeng Motor Group",
    "Reliance Industries",
    "China Southern Power Grid",
    "Target",
    "Walgreen",
    "Zurich Insurance Group",
    "Peugeot",
    "WellPoint",
    "Johnson &amp; Johnson",
    "China Development Bank",
    "Pertamina",
    "Marubeni",
    "Banco do Brasil",
    "Repsol",
    "American International Group",
    "Ping An Insurance",
    "State Farm Insurance Cos.",
    "RWE",
    "MetLife",
    "Nippon Life Insurance",
    "China Minmetals",
    "U.S. Postal Service",
    "Softbank",
    "Groupe BPCE",
    "PepsiCo",
    "Itaú Unibanco Holding",
    "Tokyo Electric Power",
    "Unilever",
    "Vodafone Group",
    "BHP Billiton",
    "China Resources National",
    "Foncière Euris",
    "Toshiba",
    "Comcast",
    "Aegon",
    "AEON",
    "Groupe Auchan",
    "Louis Dreyfus Commodities",
    "United Technologies",
    "China North Industries Group",
    "Bunge",
    "China Telecommunications",
    "Robert Bosch",
    "America Movil",
    "Aviva",
    "Wesfarmers",
    "Legal &amp; General Group",
    "CITIC Group",
    "Woolworths",
    "Google",
    "Deutsche Bank",
    "Dai-ichi Life Insurance",
    "Shenhua Group",
    "Pacific Construction Group",
    "ConocoPhillips",
    "China Post Group",
    "China South Industries Group",
    "Novartis",
    "Barclays",
    "A.P. Moller-Maersk Group",
    "Mitsui",
    "Dow Chemical",
    "CNP Assurances",
    "Seven &amp; I Holdings",
    "POSCO",
    "Aviation Industry Corp. of China",
    "OMV Group",
    "Saint-Gobain",
    "Caterpillar",
    "United Parcel Service",
    "Itochu",
    "Nippon Steel &amp; Sumitomo Metal",
    "Tewoo Group",
    "Sberbank",
    "China Communications Construction",
    "Vinci",
    "Orange",
    "Renault",
    "Pfizer",
    "Lowe's",
    "Bayer",
    "LG Electronics",
    "Intel",
    "Roche Group",
    "ThyssenKrupp",
    "Deutsche Bahn",
    "Mitsubishi UFJ Financial Group",
    "Intesa Sanpaolo",
    "Rio Tinto Group",
    "ACS",
    "Banco Bradesco",
    "UniCredit Group",
    "Sabic",
    "Banco Bilbao Vizcaya Argentaria",
    "International Petroleum Investment",
    "People's Insurance Company of China",
    "Hyundai Heavy Industries",
    "China United Network Communications",
    "Baosteel Group",
    "Korea Electric Power",
    "Energy Transfer Equity",
    "Cisco Systems",
    "SSE",
    "National Australia Bank",
    "Bank of Communications",
    "Vale",
    "Meiji Yasuda Life Insurance",
    "Enterprise Products Partners",
    "China Huaneng Group",
    "Fujitsu",
    "Aetna",
    "Coca-Cola",
    "Sumitomo Mitsui Financial Group",
    "Commonwealth Bank of Australia",
    "Aluminum Corp. of China",
    "Schlumberger",
    "Lockheed Martin",
    "Best Buy",
    "Idemitsu Kosan",
    "Walt Disney",
    "CHS",
    "Sysco",
    "Bouygues",
    "FedEx",
    "Continental",
    "Sanofi",
    "Wilmar International",
    "LyondellBasell Industries",
    "Merck",
    "Bharat Petroleum",
    "INTL FCStone",
    "Iberdrola",
    "MS&amp;AD Insurance Group Holdings",
    "Kia Motors",
    "Royal Ahold",
    "Beijing Automotive Group",
    "KDDI",
    "Anheuser-Busch InBev",
    "JBS",
    "Safeway",
    "SNCF",
    "Johnson Controls",
    "Royal Bank of Scotland Group",
    "Ingram Micro",
    "Plains GP Holdings",
    "Volvo",
    "ABB",
    "GS Caltex",
    "Tokio Marine Holdings",
    "World Fuel Services",
    "Centrica",
    "Prudential Financial",
    "GlaxoSmithKline",
    "Humana",
    "China National Building Materials Group",
    "Greenland Holding Group",
    "Denso",
    "Goldman Sachs Group",
    "HeBei Iron &amp; Steel Group",
    "Credit Suisse Group",
    "Mitsubishi Electric",
    "UBS",
    "Lufthansa Group",
    "ChemChina",
    "Jardine Matheson",
    "Sinomach",
    "Shandong Weiqiao Pioneering Group",
    "Tesoro",
    "Liberty Mutual Insurance Group",
    "Suncor Energy",
    "Honeywell International",
    "Hindustan Petroleum",
    "Huawei Investment &amp; Holding",
    "Lenovo Group",
    "Tata Motors",
    "Westpac Banking",
    "Christian Dior",
    "Shanxi Coking Coal Group",
    "United Continental Holdings",
    "Canon",
    "J. Sainsbury",
    "HCA Holdings",
    "Amer International Group",
    "Royal Bank of Canada",
    "China Guodian",
    "Deere",
    "Delta Air Lines",
    "CPC",
    "Ecopetrol",
    "Talanx",
    "State Bank of India",
    "Jizhong Energy Group",
    "Shandong Energy Group",
    "Oracle",
    "Alliance Boots",
    "Jiangsu Shagang Group",
    "Jinneng Group",
    "Wuhan Iron &amp; Steel",
    "Swiss Re",
    "Morgan Stanley",
    "Power China",
    "China National Aviation Fuel Group",
    "Hess",
    "JFE Holdings",
    "Bridgestone",
    "Twenty-First Century Fox",
    "Telecom Italia",
    "DuPont",
    "Edeka Zentrale",
    "Sears Holdings",
    "PKN ORLEN Group",
    "New York Life Insurance",
    "Vivendi",
    "DZ Bank",
    "Bohai Steel Group",
    "Henan Energy &amp; Chemical",
    "Alimentation Couche-Tard",
    "China Minsheng Banking",
    "Hanwha",
    "Mondelez International",
    "American Express",
    "Mitsubishi Chemical Holdings",
    "L.M. Ericsson",
    "Poste Italiane",
    "Magna International",
    "Industrial Bank",
    "Sistema",
    "Korea Gas",
    "Koc Holding",
    "Sumitomo Life Insurance",
    "Nationwide",
    "Allstate",
    "Zhejiang Materials Industry Group",
    "Tyson Foods",
    "Rabobank Group",
    "Shougang Group",
    "CEFC China Energy",
    "China Merchants Bank",
    "Air France-KLM Group",
    "Australia &amp; New Zealand Banking Group",
    "TIAA-CREF",
    "China Metallurgical Group",
    "Mitsubishi Heavy Industries",
    "Massachusetts Mutual Life Insurance",
    "Sinopharm",
    "Kansai Electric Power",
    "Franz Haniel",
    "Gas Natural Fenosa",
    "Toronto-Dominion Bank",
    "Sumitomo",
    "Hutchison Whampoa",
    "La Poste",
    "Xinxing Cathay International Group",
    "Guangzhou Automobile Industry Group",
    "George Weston",
    "China Huadian",
    "Datong Coal Mine Group",
    "Royal Philips",
    "Cigna",
    "Shanxi LuAn Mining Group",
    "GasTerra",
    "Standard Life",
    "Pegatron",
    "Veolia Environnement",
    "Enbridge",
    "Landesbank Baden-Württemberg",
    "DirecTV",
    "CFE",
    "Jiangxi Copper",
    "China Electronics",
    "Shanghai Pudong Development Bank",
    "China Pacific Insurance (Group)",
    "Formosa Petrochemical",
    "Shanxi Jincheng Anthracite Coal Mining Group",
    "Schneider Electric",
    "Hyundai Mobis",
    "General Dynamics",
    "Philip Morris International",
    "Yangquan Coal Industry Group",
    "Nokia",
    "China Power Investment",
    "Kailuan Group",
    "Achmea",
    "China Datang",
    "Old Mutual",
    "China Nonferrous Metal Mining (Group)",
    "3M",
    "Cosmo Oil",
    "COFCO",
    "L'Oreal",
    "China Shipbuilding Industry",
    "Accenture",
    "NEC",
    "NKSJ Holdings",
    "Delhaize Group",
    "Time Warner",
    "Quanta Computer",
    "Onex",
    "Medipal Holdings",
    "Halliburton",
    "Anglo American",
    "Suzuki Motor",
    "Mapfre Group",
    "Mizuho Financial Group",
    "Sharp",
    "Publix Super Markets",
    "Coop Group",
    "International Paper",
    "BT Group",
    "Phoenix Pharmahandel",
    "Migros Group",
    "Oil &amp; Natural Gas",
    "Power Corp. of Canada",
    "Bank of Nova Scotia",
    "S-Oil",
    "Chubu Electric Power",
    "Danone",
    "Ultrapar Holdings",
    "Aisin Seiki",
    "Shaanxi Yanchang Petroleum (Group)",
    "McDonald's",
    "Macy's",
    "Wm. Morrison Supermarkets",
    "TJX",
    "Compass Group",
    "Fluor",
    "Unipol",
    "Energie Baden-Württemberg",
    "Alstom",
    "China Railway Materials",
    "VTB Bank",
    "Fresenius",
    "East Japan Railway",
    "Northwestern Mutual",
    "Daiwa House Industry",
    "Michelin",
    "Mazda Motor",
    "Tech Data",
    "China Ocean Shipping",
    "American Airlines Group",
    "Telstra",
    "Vattenfall",
    "BAE Systems",
    "Hartford Financial Services Group",
    "Travelers Cos.",
    "Samsung Life Insurance",
    "Flextronics International",
    "Samsung C&amp;T",
    "Adecco Group",
    "Nike",
    "Heineken Holding",
    "Lotte Shopping",
    "China Energy Engineering Group",
    "Zhejiang Geely Holding Group",
    "Occidental Petroleum",
    "AstraZeneca",
    "China General Technology",
    "Standard Chartered",
    "Sumitomo Electric Industries",
    "Surgutneftegas",
    "Rite Aid",
    "Avnet",
    "Ansteel Group",
    "Showa Shell Sekiyu",
    "Perusahaan Listrik Negara",
    "Alfresa Holdings",
    "Exelon",
    "Qualcomm",
    "LG Display",
    "Emerson Electric",
    "Northrop Grumman",
    "International Airlines Group",
    "Duke Energy",
    "Tata Steel",
    "Fujifilm Holdings",
    "AntarChile",
    "Rolls-Royce Holdings",
    "TUI",
    "Agricultural Development Bank of China",
    "Capital One Financial",
    "Sodexo",
    "Fuji Heavy Industries",
    "Japan Tobacco",
    "Aflac",
    "CRH",
    "Russian Grids",
    "British American Tobacco",
    "Raytheon"
])