#!/usr/bin/env python
# Check all of the files changed and returns
# a non-zero status if there's a problem.


import os
import re
import subprocess
import sys

import pep8


try:
    from termcolor import colored  # NOQA
except ImportError:
    colored = lambda string, color=None: string  # NOQA


def run_cmd(cmd):
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                               stderr=subprocess.PIPE, shell=True)
    output, error = process.communicate()
    return output + error


def indent(string):
    if string:
        return re.sub('^', '\t', string, flags=re.M)
    else:
        return string

SUBSEQUENT_PATTERN = r"[a-z0-9]*"
CAMEL_PATTERN = r"(?:[A-Z]%s)+" % SUBSEQUENT_PATTERN
SNAKE_PATTERN = r"(?:_{0,2}[a-z]%s(?:_[a-z]%s)*_{0,2})|_" % (
                SUBSEQUENT_PATTERN, SUBSEQUENT_PATTERN)

CLASS_PATTERN = r"( {4})*class (?P<name>%s)\(" % CAMEL_PATTERN
FUNCTION_PATTERN = r"( {4})*def (?P<name>%s)\(" % SNAKE_PATTERN
LOCAL_VAR_PATTERN = r"( {4})+(?:self.)?(?P<name>%s)(?:\[[^\] ]+\])* =" % SNAKE_PATTERN
GLOBAL_VAR_PATTERN = r"(?P<name>[A-Z][A-Z_]*) ="


def extract_name(line):
    """ Extract a function or class name from line."""
    line = line.lstrip()  # strip away any leading whitespace
    if line.startswith("def ") or line.startswith("class "):
        name_w_args = line.split(" ")[1]
        actual_name = name_w_args.split("(")[0]
        return actual_name
    elif " = " in line:
        assignments = line.split(" = ")[0]
        if ', ' in assignments:
            return assignments.split(', ')
    else:
        return ''


class DelayedReport(pep8.StandardReport):

    def get_file_results(self):
        error_messages = list()
        self._deferred_print.sort()
        for line_number, offset, code, text, doc in self._deferred_print:
            error_string = "%(row)d:%(col)d: %(code)s %(text)s" % {
                'row': self.line_offset + line_number,
                'col': offset + 1,
                'code': code,
                'text': text,
            }
            line = (self.lines[line_number - 1]
                    if line_number < len(self.lines) else '')
            pointer_line = re.sub(r'\S', ' ', line[:offset]) + '^'
            if self._show_source:
                error_string = "%s\n%s\n%s" % (error_string, line,
                                               pointer_line)
            error_messages.append(error_string)

        return error_messages, self.file_errors


class CommitChecker(object):

    FIRST_COMMIT_SHA = "d0aea49773d13481943e585cf6d41067dfe8acb1"

    def __init__(self, check_all=False):
        self.check_all = check_all
        self.filename = None
        self.mimetype = None
        self.content = None
        self.lines = []
        self.errors = []
        self.pep8 = None

        self.class_re = re.compile(CLASS_PATTERN)
        self.func_re = re.compile(FUNCTION_PATTERN)
        self.local_re = re.compile(LOCAL_VAR_PATTERN)
        self.global_re = re.compile(GLOBAL_VAR_PATTERN)

    @property
    def success(self):
        return not self.errors

    @property
    def diff_options(self):
        check_against = self.FIRST_COMMIT_SHA if self.check_all else 'HEAD'
        opts = "--cached %s --name-only --diff-filter=ACMR" % check_against
        # Gets the list of file names staged for commit that have been
        # [A]dded, [C]opied, [M]odified, or [R]enamed
        return opts

    def _error(self, message):
        self.errors.append((self.filename, message))

    @property
    def _should_skip(self):
        return ('symbolic' in self.mimetype or
                self.filename.endswith('.md') or
                self.filename.endswith('.txt') or
                os.path.isdir(self.filename))

    def get_errors(self):
        return sorted(self.errors)

    def show_errors(self):
        if self.success:
            print colored('All pre-commit checks OK', 'green')
        else:
            print colored('\n' + '#'*80, 'red')
            print colored(' '*28 + 'PRE-COMMIT CHECK FAILED', 'red')
            print colored('#'*80 + '\n', 'red')

            for filename, message in self.get_errors():
                print colored('%s: %s' % (filename, message),
                              "yellow")
            print
            if os.path.exists('.git/MERGE_HEAD'):
                print colored('Since you are merging, this is only a warning. '
                              'Please fix these errors!', 'yellow')
                sys.exit(0)
            else:
                sys.exit(1)

    # MAIN RUN METHOD ---------------------------------------------------------

    def run(self):
        filenames = os.popen('git diff %s' % self.diff_options)
        for filename in filenames:
            self.filename = filename.strip()
            self.mimetype = os.popen('file --brief %s' %
                                     filename).read().strip().lower()
            # Something like "a python script text executable"

            if self._should_skip:
                continue

            self.content = file(self.filename).read()
            self.lines = self.content.split('\n')

            # TODO(Alex): use the following to just check changed lines
            # diff_full = os.popen('git diff --cached %s' %
            #                      filename).readlines()
            # diff_additions = [l for l in diff_full if l.startswith('+')]
            # diff_deletions = [l for l in diff_full if l.startswith('-')]

            print 'Checking', self.filename
            try:
                self._check_junk_file()
                self._check_pyflakes()
                self._check_pep8()
                self._check_shebang()
                self._check_conflict_marks()
                self._check_names()

            except AssertionError, e:
                self._error(e.message)

    # CHECKS #######################################################

    JUNK_FILE_RE = re.compile(r'\.( py[oc] | ~ )', re.X)

    def _check_junk_file(self):
        error_message = "You shouldn't be committing %s" % self.filename
        assert not self.JUNK_FILE_RE.search(self.filename), error_message

    def _check_pyflakes(self):
        if 'python script' in self.mimetype:
            lines_to_ignore = set()
            for num, line in enumerate(self.lines):
                if '# NOQA' in line or '# pyflakes: ignore' in line:
                    lines_to_ignore.add(str(num + 1))

            def should_warn(line):
                if ':' not in line:
                    return False
                num, _ = line.split(':', 1)
                return num not in lines_to_ignore

            output = run_cmd('pyflakes %s' % self.filename)  # Run pyflakes
            output = re.sub(r'^[^:]+:', '', output,
                            flags=re.M)  # Remove filename
            output = '\n'.join(line for line in output.split('\n')
                               if should_warn(line))
            output = indent(output)
            assert not output, "Pyflakes failed:\n%s" % output

    def _check_pep8(self):
        if self.pep8 is None:
            self.pep8 = pep8.StyleGuide()
        self.pep8.init_report(DelayedReport)
        pep8_errors, error_count = self.pep8.input_file(self.filename)
        if error_count:
            self.errors += [(self.filename, error) for error in pep8_errors]

    def _check_shebang(self):
        # XXX: I'm not sure how this plays with virtualenv,
        # but it's best practice to have the shebang
        shebang = '#!/usr/bin/env python'
        if 'python script' in self.mimetype:
            shebang_message = "First line should be '%s'" % shebang
            assert self.content.startswith(shebang), shebang_message

    def _check_names(self):
        """ Check that function/variable names use snake_case and class names
            use CamelCase.
        """
        for num, line in enumerate(self.lines):
            def match_and_check(regex, format_insertions, fallback_re=None):
                error_message = ("%(type)s name '%(name)s' isn't in %(form)s" +
                                 " form. (Line %i)" % num)
                match = regex.search(line)
                if fallback_re and not match:
                    match = fallback_re.search(line)

                # special case for multiple-assignment statements
                if type(format_insertions['name']) == list:
                    for name in format_insertions['name']:
                        match = re.match(SNAKE_PATTERN, name)
                        if not match:
                            break

                if match is None:
                    self._error(error_message % format_insertions)

            stripped = line.lstrip()
            if stripped.startswith("#") or "# NOQA" in line:
                # Don't nitpick commented out lines
                continue
            elif stripped.startswith("class"):
                match_and_check(self.class_re,
                                {'type': 'Class',
                                 'name': extract_name(line),
                                 'form': 'CapWords'})
            elif stripped.startswith("def"):
                match_and_check(self.func_re,
                                {'type': 'Function',
                                 'name': extract_name(line),
                                 'form': 'snake_case'})
            elif re.search(r"([^'\"])\s= ", line):
                match_and_check(self.local_re,
                                {'type': 'Variable',
                                 'name': extract_name(line),
                                 'form': 'snake_case'},
                                self.global_re)

    def _check_conflict_marks(self):
        if 'text' in self.mimetype:
            for num, line in enumerate(self.lines):
                if re.search(r'^(<|>|=){7}', line):
                    msg = ('There is a conflict mark in the source. Are you'
                           ' sure the merge was successful?, Line: %s' % num)
                    self._error(msg)


if __name__ == '__main__':
    checker = CommitChecker()
    checker.run()
    checker.show_errors()
